# Generated by Django 5.0 on 2024-01-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="semester",
        ),
        migrations.AddField(
            model_name="classroom",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Morning "), ("evening", "Evening")],
                default=1,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="subject",
            field=models.CharField(
                choices=[
                    ("data_mining", "Data Mining"),
                    ("ai", "AI"),
                    ("graphic_design", "Graphic Design"),
                    ("computerized accounting", "Computerized Accounting"),
                ],
                max_length=50,
                verbose_name="Subject Name",
            ),
        ),
    ]
