# Generated by Django 5.0.2 on 2024-03-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_classroom_semester_classroom_shift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="subject",
            field=models.CharField(
                choices=[
                    ("data_mining", "Data Mining"),
                    ("ai", "AI"),
                    ("UI/UX", "UI/UX"),
                    ("computerized accounting", "Computerized Accounting"),
                ],
                max_length=50,
                verbose_name="Subject Name",
            ),
        ),
    ]
